mysite/mysite/course/urls.py
from django.urls.conf import path, re_path
from django.views.generic.base import TemplateView

from .views import AboutView, CreateLessonView,ListLessonsView
from .views import CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView


urlpatterns = [
    #没有直接使用 TemplateView（template_name=＂course/about.html＂）的方式
    #因为path中url解析只认识函数方式,不能解析实例化类的模式
    path('about/',AboutView.as_view(),name='about'),
    path('course_list/',CourseListView.as_view(),name='course_list'),
    path('manage_course/',ManageCourseListView.as_view(),name='manage_course'),
    path('create_course/',CreateCourseView.as_view(),name='create_course'),
    re_path('delete_course/(?P<pk>\d+)/',DeleteCourseView.as_view(),name='delete_course'),
    path('create_lesson/',CreateLessonView.as_view(),name='create_lesson'),
    re_path('list_lessons/(?P<course_id>\d+)/',ListLessonsView.as_view(),name='list_lessons'),
    re_path('detail_lesson/(?P<lesson_id>\d+)/',CreateLessonView.as_view(),name='detail_lesson'),
    
    ]

mysite/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.urls import re_path
from django.views.generic.base import RedirectView, TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    # path('blog/', views.blog_title,name='blog_title'), # 访问url,响应请求的函数,
    re_path(r'^$', include(('blog.urls','blog'),namespace='blog')),
    re_path(r'blog/', include(('blog.urls','blog'),namespace='blog')),#appname=blog namespace='blog'
    #appname=blog namespace='blog'
    re_path(r'account/', include(('account.urls','account'),namespace='account')),
    # re_path(r'^accounts/login/$', auth_views.LoginView.as_view(),name='user_login'),
    path("account/password_change_done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),#auth_view函数需要
    path("password_reset/", include(('password_reset.urls','password_reset'),namespace='password_reset')),
    path("article/", include(('article.urls','article'),namespace='article')),
    path("saveimage/", include(('saveimage.urls','saveimage'),namespace='saveimage')),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'/static/favicon.ico')),
    path(r'home/', TemplateView.as_view(template_name='home.html'),name='home'),
    path(r'course/', include(('course.urls','course'),namespace='course')),
    
    
]
# MEDIA_URL /media/' 定义/media/的绝对路径
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/mysite/saveimage/urls.py
# coding:utf-8
'''
Created on 2024年1月26日

@author: ZhiGangDLZhao
'''
from django.urls.conf import path

from . import views


urlpatterns=[
    path('list_images/',views.list_images,name="list_images"),
    path('upload_image/',views.upload_image,name='upload_image'),
    path('del_image/',views.del_image,name='del_image'),
    path('falls_images/',views.falls_images,name='falls_images'),    
    
    ]

mysite/mysite/course/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from slugify import slugify
from .fields import OrderField

# Create your models here.
class Course(models.Model):
    user= models.ForeignKey(User,related_name="course_user",on_delete=CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('-created',)
    def save(self,*args,**kargs):
        self.slug = slugify(self.title)
        super(Course,self).save(*args,**kargs)
    def __str__(self):
        return self.title
def user_dir_path(instance,filename): #instance是一个实例
        return "courses/user_{0}/{1}".format(instance.user.id,filename)    
#课程类
class Lesson(models.Model):
    user=models.ForeignKey(User,related_name="lesson_user",on_delete=CASCADE)  
    course = models.ForeignKey(Course,related_name="lesson",on_delete=CASCADE) 
    title=models.CharField(max_length=200) 
    video=models.FileField(upload_to=user_dir_path) #定义相对文档根目录的子文件夹
    description = models.TextField(blank=True)
    attach= models.FileField(blank=True,upload_to=user_dir_path)
    created = models.DateTimeField(auto_now_add=True)
    order=OrderField(blank = True,for_fields=['course']) #目标字段是course,
    
    class Meta:
        ordering=['order']
    def __str__(self):
        return '{}.{}'.format(self.order,self.title)
    
    
    

mysite/mysite/course/forms.py
from django import forms
from .models import Course,Lesson

class CreateCourseForm(forms.ModelForm):
    class Meta:
        model= Course
        fields=('title','overview') #form中创建2个字段用于输入,其他的有系统处理

class CreateLessonForm(forms.ModelForm):    
    class Meta:
        model = Lesson
        fields = ['course','title','video','description','attach']
    def __init__(self,user,*args,**kwargs):    
        #初始化函数提前把这个课的主题按照相同用户筛选出来
        super(CreateLessonForm,self).__init__(*args,**kwargs)
        self.fields['course'].queryset = Course.objects.filter(user=user)

mysite/mysite/course/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls.base import reverse_lazy
from django.views.generic.base import TemplateView, View, TemplateResponseMixin
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView

from .forms import CreateCourseForm, CreateLessonForm
from .models import Course, Lesson


# Create your views here.
class AboutView(TemplateView):
    template_name="course/about.html"
    
class CourseListView(ListView):
    model = Course #list数据是course的所有数据
    context_object_name="courses" #定义传入模板网页的变量名称,如果没有定义默认是object
    template_name="course/course_list.html"
    
class UserMixin:  #默认继承Object类
    def get_queryset(self):
        qs = super(UserMixin,self).get_queryset()
        return qs.filter(user=self.request.user)
    
class UserCourseMixin(UserMixin,LoginRequiredMixin): #继承
    model = Course
    login_url='/account/login/'
    
class ManageCourseListView(UserCourseMixin,ListView):#继承,有queryset和model=course变量
    context_object_name = "courses"
    template_name='course/manage/manage_course_list.html'
    
class CreateCourseView(UserCourseMixin,CreateView):      #继承关联course 和自动登录功能,CreateView自动创建新form响应GET方法
    fields=['title','overview']  #create view专用设定
    template_name='course/manage/create_course.html' 
    
    def post(self,request,*args,**kargs):
        form = CreateCourseForm(data=request.POST) #根据用户入力数据填充
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user= request.user
            new_course.save()
            return redirect("course:manage_course")  #成功后重定向
        return self.render_to_response({'form':form}) #使用form 返回原来请求路径 重新填写
    
    
class DeleteCourseView(UserCourseMixin,DeleteView):
    
    #get方法根据url中pk参数 生成对象form迁移到confirm.html
    #pk = self.kwargs.get(self.pk_url_kwarg)
    #删除确认模板
    template_name='course/manage/delete_course_confirm.html'
    #POST处理删除成功后迁移path
    success_url=reverse_lazy("course:manage_course")
    
    # def post(self, request, *args, **kwargs):
    #     print("**********kwargs",kwargs)
    #     return super(DeleteCourseView,self).post(request, *args, **kwargs)
    
    def dispatch(self, *args, **kwargs):
        #原本DeleteView执行dispatch后重定向到success_url,重写后截取response,返回json result=OK,ajax处理
        resp = super(DeleteCourseView,self).dispatch(*args,**kwargs)
        if self.request.is_ajax:
            
            response_data = {"result":"ok"}
            return HttpResponse(json.dumps(response_data),content_type="application/json")
        else:
            return resp
        
        
class CreateLessonView(LoginRequiredMixin,View):    
    model = Lesson
    login_url="/account/user_login/"
    
    def get(self,request,*args,**kwargs):
        form = CreateLessonForm(user=self.request.user)
        return render(request,"course/manage/create_lesson.html",{'form':form})
    
    def post(self,request,*args,**kwargs):
        #user,*args,**kwargs):   
        form = CreateLessonForm(self.request.user,request.POST,request.FILES)
        #自动根据字段名填充form
        if form.is_valid():
            new_lesson = form.save(commit=False)
            new_lesson.user=self.request.user
            new_lesson.save()
            return redirect("course:manage_course")
        
class ListLessonsView(LoginRequiredMixin,TemplateResponseMixin,View):    
    login_url = "/account/user_login"
    template_name='course/manage/list_lessons.html'    
    
    #根据课程id取得课程对象,html中课程对象的所有上课内容
    def get(self,request,course_id):   
        course = get_object_or_404(Course,id=course_id)
        return self.render_to_response({'course':course})
        
    

mysite/mysite/saveimage/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import SaveImageForm
from .models import SaveImage


# Create your views here.
@login_required(login_url='/account/user_login/')
@csrf_exempt #不是表单,需要豁免
@require_POST
def upload_image(request):
    #提交保存图片
    # ajax传来的数据是字典 {"title":title,"url":url,"description":description}
    form = SaveImageForm(data=request.POST) #使用字典类键值对填充form
    if form.is_valid():
        #数据验证成功
        try:
            new_item=form.save(commit=False)#先保存form中提交字段部分,返回model对象 image对象得到处理
            new_item.user=request.user #user得到处理
            new_item.save() #db 保存,增加slug得到处理
            return JsonResponse({'status':"0"})
        except Exception as e:
            print("********************",e)
            return JsonResponse({'status':"1","error":e.__str__()})
@login_required(login_url='/account/uesr_login')    
def list_images(request):    
    #显示所有图片
    images = SaveImage.objects.filter(user=request.user)
    return render(request,'saveimage/list_images.html',{'images':images})


#删除图片
@login_required(login_url='/account/user_login/')
@csrf_exempt #不是表单,需要豁免
@require_POST
def del_image(request):
    #提交保存图片
    img_id = request.POST['img_id']
    
    #数据验证成功
    try:
        image = SaveImage.objects.get(id=img_id)
        # image.image.path= 每个文件或图片文件都有path属性 upload_to设定相对路径
        # /home/zzg/mysite/mysite/media/images/2024/0127/shuimu.jpg
        image.delete()
        return JsonResponse({'status':"0"})
    except Exception as e:
        print("********************",e)
        return JsonResponse({'status':"1","error":e.__str__()})
    
def falls_images(request):
    images= SaveImage.objects.all()
    return render(request,'saveimage/falls_images.html',{'images':images})
            

mysite/mysite/templates/saveimage/falls_images.html
{% extends 'base.html' %}
{% load static %}
{% block title %}images{% endblock %}
{% block content %}

<div class="container">
<link rel='stylesheet' href="{% static 'css/mansory-style.css' %}" type="text/css" />
<div id='my-gallery-container'>
	{% for image in images %}
	<div class="falls_item h200" data-order="{{image.id}}">
		<img src="{{image.image.url}}">
		<p>{{image.title}}</p>
		
	</div>
	{% endfor %}
	

</div>
</div>


<script src='{% static "js/jquery.js" %}'></script> 
<script src="{% static 'js/mp.mansory.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript"> 
jQuery(document).ready(function($) {
	$("#my-gallery-container").mpmansory({
		childrenClass : 'falls_item',
		columnClasses:'falls_padding',
		breakpoints:{
			lg:3,
			md:4,
			sm:6,
			xs:12
			},
		distributeBy:{order:false,height:false,attr:'data-order',attrOrder:'desc'},
		})

	})



</script>

{% endblock %}

mysite/mysite/templates/saveimage/list_images.html
{% extends 'article/base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}images{% endblock %}
{% block content %}
<div>
	<button type="button" class="btn btn-primary btn-lg btn-block" onclick="addImage()">Add a Image</button>
	<div style="margin-top:10px;">
		<table class="table table-hover">
			<tr>
				<td>No.</td>
				<td>Title</td>
				<td>image</td>
				<td>manage</td>
			</tr>
			{% for img in images %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{img.title}}</td>
				{% thumbnail img.image "100x100" as im %}
				<td><img src="{{im.url}}" ></td>
				{% endthumbnail %}
				<td>
				<a id='delete' href="javascript:" onclick="del_image(this,{{img.id}})">
					<span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
				</a>
				
				</td>
			</tr>
			{% empty %}
			<p>There is no image yet</p>
			{% endfor %}
		</table>	

</div>
<script src="{% static 'js/jquery.js' %}" ></script>
<script src="{% static 'js/layer.js' %}" ></script>
<script type="text/javascript">
function addImage(){
	var index=layer.open({
		type:1,
		skin: 'alyui-layer-demo',
		closeBtn:0,
		shift:2,
		shadeClose:true,
		title:'Add a Image',
		area:['600px','440px'],
		content:"<div style='padding:20px'><p>please input .jpg or .png url</p><form><div class='form-group'><label for='phototitle' class='col-sm-2 control-label'>title</label><div class='col-sm-10'><input id='phototitle' type='text' class='form-control' style='margin-bottom:5px'></div></div><div class='form-group'><label for='photourl' class='col-sm-2 control-label'>URL</label><div class='col-sm-10'><input id='photourl' style='margin-bottom:5px' type='text' class='form-control'></div></div><div class='form-group'><label for='description' class='col-sm-2 control-label'>Description</label><div class='col-sm-10'><textarea class='form-control' style='margin-bottom:5px' rows='2' id='photodescription'></textarea></div></div><div class='form-group'><div class='col-sm-offset-2 col-sm-10'><input id='newphoto' type='button' class='btn btn-default' value='add it'></div></div></form><div>",
		success:function(){
			$("#newphoto").on('click',function(){
				var title=$("#phototitle").val();
				var url=$("#photourl").val();
				var description=$("#photodescription").val();
				var photo = {"title":title,"url":url,"description":description};//字典类
				$.ajax({
					url:'{% url "saveimage:upload_image" %}',
					type:"POST",
					data:photo,
					success:function(e){//返回的e是个json response
						var status = e['status'];
						
						if(status == '0'){
							layer.close(index);
							window.location.reload();
							
						} else {
							var error = e['error'];
							//alert(error);
							layer.msg("save failed, reason:"+error);
						}
					},//function
				});//ajax
			});  //on function
		},
	}); //var index=layer.open({
	
}//addimage
//控件对象和id
function del_image(the,img_id){
	//编辑图标的父类tr,下面第一个td的text 得到name
	var name = $(the).parents("tr").children("td").eq(1).text()
	var index=layer.open({
		type:1,
		skin:"layui-layer-rim",
		area:["400px","200px"],
		title: "del column",
		content:'<div class="text-center" style="margin-top:20px"><p>are you sure to delete image: "'+name+'"</p></div>',
		btn:['OK','cancel'],
		yes:function(index,layero){
			
			//调用ajax异步提交
			$.ajax({
				url:'{% url "saveimage:del_image" %}',
				type:'POST',
				data:{"img_id":img_id},
				success:function(e){
					var status = e['status'];
					if(status=='0'){
						parent.location.reload();
						layer.msg(name+"is deleted");
					}else{
						var error=e['error']
						layer.msg("delete failed becase:"+error)
					}
				},
			});

		},
		//取消按钮
		btn2:function(index,layero){
			layer.close(index);
		}		
	});	
}
</script>
{% endblock %}